//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline_Ticket_Booking.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGE
    {
        public string MessageID { get; set; }
        public string TexterID { get; set; }
        public string RecipientID { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
    }
}
